### ISSUE TITLE
Add Number of Annotated and Unannotated Plates

### ISSUE THREAD

**Issue by alimirzaei** [reza-agahi/LPR-annotator#1]
Add sum statistics about progress of annotating like:
1- Number of annotated plates
2- Number of unannotated plates
3- Progress Percent (optional)

**Comment by reza-agahi** [comment]
Feature #1 is added before.
Feature #2 and #3 is not desirable because annotators are not happy with seeing the glass half empty of all plates. Instead we should add a mechanism to share a certain amount of data to each annotator and then add these features for that subset of all plates.
