### ISSUE TITLE
اضافه کردن قابلیت ثبت حرف های ناخوانا

### ISSUE THREAD

**Issue by alimirzaei** [reza-agahi/LPR-annotator#2]
در بعضی از مواقع پیش می آید که پلاکی ناقص بوده یا یک حرف از آن خوانده نمی شود. در چنین شرایط کار معقولی نیست که آن پلاک به عنوان پلاکی که قابل نشانه گذاری نیست ثبت شود و داده های ان را دور بریزیم. در چنین شرایطی باید بتوان یک عدد یا کاراکتر را بصورت قراردادی به جای حرف ناخوانا قرار داد.

**Comment by reza-agahi** [comment]
This capability is added now;)
